fx = FxList.new("a", "adsr", {"a":0, "r":1, "sus": 1}, order=2)
fx.add_var("env")
fx.add("env = EnvGen.ar(Env.new(levels: [0,1,1,0], times:[a*sus, sus - a*sus - r*sus, r*sus], curve: 'lin'))")
fx.add("osc = osc*env")
fx.save()